version: "3"
services:
  registrator:
    image:
       gliderlabs/registrator:latest
    network_mode: "host"
    container_name: "registrator"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: "consul://127.0.0.1:8500"
    depends_on:
      - consul

  consul:
    image: consul
    container_name: "consul"
    command: "agent -server -client=127.0.0.1 -bind=127.0.0.1 -ui -bootstrap"
    network_mode: "host"
    expose:
      - 8500
      - 8600
    ports:
      - 8500
      - 8600
